config/routes.rb
Rails.application.routes.draw do
 
 # post 'messages', to: 'messages#create'
  
  get 'user/show'

  
 # post	''POST	/chatrooms/:chatroom_id/messages(.:format)
# put '/chatrooms/:id/messages' => 'messages#create'
 
  resources :chatrooms do
   
  end
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "chatrooms#index"
   
   resources :user
   resources :messages
   

   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
    has_many :messages
    has_many :users
    validates_uniqueness_of :name
    scope :public_chatroooms,-> {where(is_private: false)}
    after_create_commit {broadcast_append_to "chatooms"}
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :username, uniqueness: true, presence: true
         has_many :chatrooms
         has_many :messages
         scope :public_user,-> {where.not(id: user)}
         after_create_commit { broadcast_append_to "users" }
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  # GET /chatrooms or /chatrooms.json
  def index
    
    @chatrooms = Chatroom.all
    @users = User.all
   
     
  end

  # GET /chatrooms/1 or /chatrooms/1.json
  def show
    
    @chatroom = Chatroom.find(params[:id])
    @messages = Message.all
   # render  @users
 
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit

  end

  # POST /chatrooms or /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.save
        format.html { redirect_to chatroom_url(@chatroom), notice: "Chatroom was successfully created." }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1 or /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to chatroom_url(@chatroom), notice: "Chatroom was successfully updated." }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1 or /chatrooms/1.json
  def destroy
    @chatroom.destroy

    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: "Chatroom was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chatroom_params
      params.require(:chatroom).permit(:name)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
    @chatroom = Chatroom.find(params[:id])
    @chatrooms = Chatroom.all
  
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to message_url(@message), notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:body, :user_id, :chatroom_id)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  
  def show
    @user = User.all
    @user = User.find(params[:id])
  
   

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/chatrooms/_chatroom.html.erb
<div class="container">
<div class="card text-bg-outline-secondary mb-3" style="max-width: 18rem;">
<div class="card-header"></div>
<div class="card-body">
<div class="text-black ">
<%= link_to chatroom.name,chatroom %><br>
<%chatroom.messages.each do |message|  %>
    
<%= message.body%> 
<%=message.user.username%>
<br>
<%end%>
</div>
</div>
</div>
</div>
</div>

app/views/chatrooms/_form.html.erb
<%= form_with(model: chatroom) do |form| %>
  <% if chatroom.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
        <% chatroom.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<h1>Editing chatroom</h1>

<%= render "form", chatroom: @chatroom %>

<br>

<div>
  <%= link_to "Show this chatroom", @chatroom %> |
  <%= link_to "Back to chatrooms", chatrooms_path %>
</div>

app/views/chatrooms/index.html.erb
<p style="color: green"><%= notice %></p>
<% if user_signed_in? %> 
 <div> Welcome <%= current_user.email %> </div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>

<h1>Chat-Rooms-List</h1>

<div id="chatrooms">
  <% @chatrooms.each do |chatroom| %>
  <%= render chatroom%>
  <% end %>
</div>

 
 <div  class="btn btn-light"> 
<%= link_to "Create Chat", new_chatroom_path%>
</div>



<div class="btn btn-outline-light">
 <% @users.each do|user|%>

    
<%= link_to user.email, user %>

<%end%>
</div>

app/views/chatrooms/new.html.erb
<%= render "form", chatroom: @chatroom %>

<div class="btn btn-warning">
  <%= link_to "Back to chatrooms", chatrooms_path %>
</div>

app/views/chatrooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @chatroom %>


<div>
  <%= link_to "Edit this chatroom", edit_chatroom_path(@chatroom) %> |
  <%= link_to "Back to chatrooms", chatrooms_path %>
 <%= link_to "Show this chatroom",  chatrooms: @message%>
  <%= button_to "Destroy this chatroom", @chatroom, method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Babble-Messenger</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">ChatRooms</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/messages">Messages</a>
        </li>
   
   
    </div>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>BabbleMessenger</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       
  </head>

  <body>
  
  <%= render "layouts/navbar"%>
    <%= yield %>
    
  </body>

</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>
 <%#= form.hidden_field :user_id, value: current_user.id %>
 
  <div>
    <%= form.label :user_id, style: "display: block" %>
  
    <%= form.select :user_id, Chatroom.all.map{ |w| [w.id ] }%>
  </div>

  <div>
    <%= form.label :chatroom_id, style: "display: block" %>
    <%= form.select :chatroom_id, Chatroom.all.map{ |w| [ w.name, w.id ] } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p>
    <strong>Body:</strong>
    <%= message.body %>
  </p>

  <p>
    <strong>User:</strong>
    <%= message.user_id %>
  </p>

  <p>
    <strong>Chatroom:</strong>
    <%= message.chatroom_id %>
  </p>

</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div class="btn btn-light" >
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
  <%= link_to "Back to chatrooms", chatrooms_path %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <p>
      <%= link_to "Show this message", message %>
    </p>
  <% end %>
</div>
<div class="btn btn-info">
<%= link_to "New message", new_message_path %>
</div>

app/views/messages/new.html.erb
<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div class ="btn btn-light">
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container text-center">
  <div class="row align-items-start">
    <div class="col">
  
  <%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>
</div>

app/views/user/_user.html.erb
<div >
  <%#= link_to user.email, user %> 
  


  
 </div>
<%#= link_to chatroom.message, @chatrooom%>

app/views/user/show.html.erb
<div class="chatroom_container">

<h1>Hi</h1>

<%=@user.username%>
</div>

 <%= turbo_stream_from @chatrooms %>
<div id="messages">
</div>

<div class="container">
<h2>Messages</h2>
<table>
  <thead>
  <tr>
  
    
    <th>Body:</th>
    <th>User_id:</th>
    <th>Chatroom_id:</th>

    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <%  @user.messages.each do |message| %>
  
      <tr>
     
        <td><%= message.body %></td>
        <td><%= message.user_id %></td>
        <td><%= message.chatroom_id %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= button_to "Destroy", @message, method: :delete, data: { turbo_confirm: "Are you sure?"} %></td>
        <td><%= link_to "Back to messages", messages_path %></td>
         <td><%= link_to "Back to chatrooms", chatrooms_path %></td>

      </tr>
    <% end %>
  </tbody>
</table>